version: "3.8"

services: 
  app:
    image: "alpine:latest"
    container_name: main_app
    ports: 
      - "8080:8080"
    volumes: 
      - app_logs:/var/log/app
    command: ["sh", "-c", "mkdir -p /var/log/app && while true; do echo $(data) ' - 로그 메시지 예제' >> /var/log/app/app.log; sleep 2; done"]

  log-collector: 
    image: fluent/fluentd
    container_name: sidecar_logger
    depends_on:
      - app
    volumes:
      - app_logs:/fluentd/log
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"

volumes: 
  app_logs:



